# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: shogomorisawa
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: oox
service: laravel

# Set your team ID if you are using Bref Cloud
#bref:
#    team: my-team-id

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: ap-northeast-1
    # Environment variables
    environment:
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage
        APP_KEY: ${env:APP_KEY} # .envのキーを使う
        SESSION_DRIVER: cookie # Change to database if you have set up a database
        QUEUE_CONNECTION: database
        CACHE_STORE: database # Lambda環境ではfileドライバは使えないため、databaseを明示的に指定
        GEMINI_REQUEST_TIMEOUT: 600 # Geminiを10分待つように設定
        # DB設定（.envの値をそのままAWSに渡す設定）
        DB_CONNECTION: pgsql
        DB_HOST: ${env:DB_HOST}
        DB_PORT: ${env:DB_PORT}
        DB_DATABASE: ${env:DB_DATABASE}
        DB_USERNAME: ${env:DB_USERNAME}
        DB_PASSWORD: ${env:DB_PASSWORD}

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!resources/css/**'
        - '!resources/images/**'
        - '!resources/js/**'
        - '!storage/**'
        - '!tests/**'
        - '!database/*.sqlite'
        # Exclude assets except for the manifest file
        - '!public/build/**'
        - 'public/build/manifest.json'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-82-fpm
        layers:
            - ${bref:layer.php-82}
            - ${bref:extra.pgsql-php-82}  # PostgreSQLドライバ
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-82-console
        layers:
            - ${bref:layer.php-82}
            - ${bref:extra.pgsql-php-82}  # PostgreSQLドライバ
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

    # This function processes queued jobs every minute
    worker:
        handler: artisan
        runtime: php-82-console
        layers:
            - ${bref:layer.php-82}
            - ${bref:extra.pgsql-php-82}  # PostgreSQLドライバ
        timeout: 720 # 12分（これならGeminiが長考しても大丈夫！）
        events:
            - schedule:
                rate: rate(1 minute)
                input: '"queue:work --stop-when-empty --max-time=600"'

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
